name: Auto Create PRs for Clients

on:
  push:
    tags:
      - 'release*'

jobs:
  create_prs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client_branch: [cliente1, cliente2, cliente3]

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Fetch and prepare PR branch
        run: |
          git fetch origin ${{ matrix.client_branch }}:${{ matrix.client_branch }}
          git checkout -b auto-merge/main-to-${{ matrix.client_branch }} ${{ matrix.client_branch }}
          if git merge origin/main --no-edit; then
            echo "CONFLICT=false" >> $GITHUB_ENV
          else
            echo "CONFLICT=true" >> $GITHUB_ENV
            git merge --abort
          fi
          git push origin auto-merge/main-to-${{ matrix.client_branch }}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPPERCASE_BRANCH=$(echo "${{ matrix.client_branch }}" | tr '[:lower:]' '[:upper:]')
          
          CURRENT_DATE=$(date +%d/%m/%Y)
          
          PR_TITLE="ATUALIZAÇÃO ${UPPERCASE_BRANCH} - ${CURRENT_DATE}"
          
          gh pr create \
            --title "$PR_TITLE" \
            --body "Este PR foi criado automaticamente da main para ${{ matrix.client_branch }}.

          ## 🔍 O que fazer:
          1. Revise as mudanças
          2. Assine o PR
          3. Faça merge do PR

          ## 📝 Detalhes:
          - Branch origem: \`main\`
          - Branch destino: \`${{ matrix.client_branch }}\`
          - Tag que disparou: \`${{ github.ref_name }}\`
          - Conflitos: $([ \"$CONFLICT\" == \"true\" ] && echo \"Sim\" || echo \"Não\")" \
                      --base ${{ matrix.client_branch }} \
                      --head auto-merge/main-to-${{ matrix.client_branch }} \